SukBakJi/SukBakJi-iOS

.gitignore

- xcuserdata 폴더 및 .xcuserstate 파일을 .gitignore에 추가하여 Git에서 추적하지 않도록 설정했습니다.

.gitignore 폴더 생성 및 *.xcuserstate & xcuserdata/ 추가

---

Sukbakji/DataLayer/DataManagers/UserAPI/UserDataManager.swift

[fix] 학력인증 API 헤더 수정

---

Sukbakji.xcodeproj/project.pbxproj
Sukbakji/DataLayer/DataManagers/UserAPI/UserDataManager.swift
Sukbakji/DataLayer/DataManagers/UserAPI/UserRequest.swift
Sukbakji/DataLayer/DataManagers/UserAPI/UserResponse.swift
Sukbakji/PresentationLayer/Sources/Login/ViewControllers/LoginViewController.swift
Sukbakji/PresentationLayer/Sources/SignUp/ViewControllers/SignupViewController.swift
Sukbakji/PresentationLayer/Sources/SignUp/ViewControllers/TOSViewController.swift
Sukbakji/PresentationLayer/Sources/SignUp/Views/TOSView.swift

- 애플 로그인 시 회원가입 및 로그인 처리 완료
- 소셜 로그인 시 전화번호 인증 과정 제외

Feat/applelogin 

---

Sukbakji/DataLayer/Extensions/AuthInterceptor+.swift

- AuthInterceptor 내 API 연결 함수의 parameter 이름 수정
-

[fix] 리프레시 토큰 요청 시 json 수정

---

Sukbakji/PresentationLayer/Sources/Board/Main/DummyBoardDetail.swift

- 내가 스크랩한 게시물 API의 postId를 통해, 내가 스크랩한 게시물의 북마크 이미지가 노란색으로 채워져 보이도록 성공함.
- close #222

[feat] 게시물 북마크 버튼 반영

---

Sukbakji/PresentationLayer/Sources/Directory/DirectoryMainViewController.swift
Sukbakji/PresentationLayer/Sources/Directory/DirectoryModel/DirectoryLabSearchModel.swift
Sukbakji/PresentationLayer/Sources/Directory/DirectorySearchViewController.swift
Sukbakji/PresentationLayer/Sources/Directory/LabDetailReviewViewController.swift
Sukbakji/PresentationLayer/Sources/Directory/LabDetailViewController.swift
Sukbakji/PresentationLayer/Sources/Directory/LabReviewViewController.swift

- 네비게이션 바 제거
- symbol 이미지 오타 수정
- 연구실 홈페이지 바로가기 기능 추가 (Safari 연결)
- 연구실 후기 UI 레이아웃 수정
- 라벨 UI 수정
- 연구실 스크랩 즉시 반영 (NotificationCenter 사용)
- 북마크 상태 불러오기 API 연동
- 검색 UX 업데이트
- 대학교 정렬 필터링 수정 및 UI 수정
- '연구실 더보기' 더보기 버튼 누르면 3개씩 표시하고 더 이상 표시할 것이 없을 때 숨김
- 연구실 상단화면 Divider() 추가
- 연구실 정보 화면 세그먼트 컨트롤 좌우 스크롤 추가
- close #188

[feat] 디렉토리 api 정상화 및 ui 보완

---

Sukbakji/PresentationLayer/Sources/Board/BoardViewController.swift
Sukbakji/PresentationLayer/Sources/Board/Doctoral/BoardDoctoralViewController.swift
Sukbakji/PresentationLayer/Sources/Board/DummyBoards.swift
Sukbakji/PresentationLayer/Sources/Board/Main/BoardMainViewController.swift
Sukbakji/PresentationLayer/Sources/Board/Main/BoardQnAViewController.swift
Sukbakji/PresentationLayer/Sources/Board/Main/CommentedBoardViewController.swift
Sukbakji/PresentationLayer/Sources/Board/Main/HotBoardViewController.swift
Sukbakji/PresentationLayer/Sources/Board/Main/WrittenBoardViewController.swift
Sukbakji/PresentationLayer/Sources/Board/SearchViewController.swift

- 세그먼트 컨트롤
- UI 피그마와 통일
- close #227

[feat] 게시판 UI/UX 수정

---

Sukbakji/DataLayer/Repositories/HomeRepository.swift
Sukbakji/PresentationLayer/Sources/Home/View/MyPage/EditPWViewController.swift
Sukbakji/PresentationLayer/Sources/Home/View/MyPage/ProfileTabViewController.swift
Sukbakji/PresentationLayer/Sources/Home/ViewModel/MyProfileViewModel.swift

[modify] 비밀번호 변경 API 테스트 완료 (#231)

---

Sukbakji/PresentationLayer/Sources/Directory/DirectorySearchViewController.swift
Sukbakji/PresentationLayer/Sources/Directory/LabReviewViewController.swift
Sukbakji/PresentationLayer/Sources/Directory/ScrappedLabDetailViewController.swift

- UI 피그마와 통일
- 검색 api 기존 6개 불러오는 것에서 1000으로 증가
- close #233

[feat] 연구실 UI 수정 및 검색 api 수정

---

Sukbakji/PresentationLayer/Sources/Directory/DirectoryMainViewController.swift
Sukbakji/PresentationLayer/Sources/Directory/DirectorySearchViewController.swift
Sukbakji/PresentationLayer/Sources/Directory/LabReviewViewController.swift

- KeywordView의 강제로 한줄로 표시하기 때문에 좌우 여백이 제대로 적용되지 않았음
- close #236

[fix] 디렉토리 UI 깨짐 현상 해결

---

Sukbakji/DataLayer/DataManagers/AuthAPI/AuthDataManager.swift

[fix] 로그인 실패 시 실패 문구 안 보이는 에러 해결 완 (#244)

---

Sukbakji/PresentationLayer/Sources/Directory/LabDetailReviewViewController.swift

[feat] 연구실 후기 작성 페이지에서 탭바 숨김

---

Sukbakji/PresentationLayer/Sources/Home/View/MyPage/MypageViewController.swift

[fix] 자동 로그인 수정 후 로그아웃 안 되는 문제

---

Sukbakji/DataLayer/DataManagers/UserAPI/UserDataManager.swift
Sukbakji/PresentationLayer/Sources/Login/ViewControllers/LoginViewController.swift

- apple-login Email 보내주는 API 삭제
-

[fix] apple-login Email 보내주는 API 삭제

---

Sukbakji/PresentationLayer/Sources/Board/Main/DummyBoardDetail.swift

- 액션시트 ZStack으로 커스텀
- CommentMoreButtonView 구현
-

[feat] 댓글 신고하기 UI 완성

---

Sukbakji/DataLayer/DataManagers/AuthAPI/AuthDataManager.swift
Sukbakji/PresentationLayer/Sources/Login/ViewControllers/LoginViewController.swift
Sukbakji/PresentationLayer/Sources/SignUp/AcadmicVerification/AcademicVerificationViewController.swift
Sukbakji/PresentationLayer/Sources/SignUp/ViewControllers/TOSViewController.swift

[feat] 애플 로그인 시 사용자 이름 필드에 고정

---

Sukbakji/PresentationLayer/Sources/Home/View/Home/HomeViewController.swift
Sukbakji/PresentationLayer/Sources/SignUp/ViewControllers/CompleteViewController.swift

- 회원가입 시에서 로그인 완료 후 fcm 토큰이 발급되도록 수정

[modify] 로그인 완료 후 fcm토큰 발급 (#243)

---

Sukbakji/PresentationLayer/Sources/SignUp/AcadmicVerification/SecondAcademicVerificationViewController.swift
Sukbakji/PresentationLayer/Sources/SignUp/AcadmicVerification/ThirdAcademicVerificationViewController.swift

[fix] 학력인증 이미지 업로드 에러 해결

---

Sukbakji.xcodeproj/project.pbxproj
Sukbakji/DataLayer/Extensions/AuthInterceptor+.swift
Sukbakji/DataLayer/Extensions/RefreshTokenManager+.swift
Sukbakji/DesignSystem/Extensions/Notification+.swift
Sukbakji/SUKBAKJI/Sources/SceneDelegate.swift

[fix] 카카오톡 로그인/리프레시 에러

---

Sukbakji/DesignSystem/Components/Home/HomeView.swift
Sukbakji/DesignSystem/Components/Home/MyPageView.swift
Sukbakji/PresentationLayer/Sources/Board/Main/DummyBoardDetail.swift
Sukbakji/PresentationLayer/Sources/Board/ViewModel/ReportViewModel.swift
Sukbakji/PresentationLayer/Sources/Home/View/Home/HomeViewController.swift
Sukbakji/PresentationLayer/Sources/Home/View/MyPage/MypageViewController.swift

- 마이페이지 문의하기 기능 추가
- 게시글, 댓글 신고 완료 시 팝업 창 띄우기

[feat] 마이페이지 문의하기 버튼 추가 및 게시글, 댓글 신고 팝업창 추가 (#254)

---

Sukbakji/PresentationLayer/Sources/SignUp/AcadmicVerification/FirstAcademicVerificationViewController.swift
Sukbakji/PresentationLayer/Sources/SignUp/AcadmicVerification/SecondAcademicVerificationViewController.swift
Sukbakji/PresentationLayer/Sources/SignUp/AcadmicVerification/ThirdAcademicVerificationViewController.swift
Sukbakji/SUKBAKJI/Resources/Info.plist

- Info.plist 에서 사진 허용 설정 켜줌
- 이미지 확장자, 파일명, 크기 라벨 정보 수정

[fix] 사진 찍기 크래시 해결 - Info.plist 수정
